# Generated by Django 5.2.8 on 2025-12-04 13:28

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PagesSpeedTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField()),
                ('user_ip', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('result_file', models.FilePathField(path='data', recursive=True)),
                ('access_link', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
    ]
